### ISSUE TITLE
backporting phpcbf for v8.0.x

### ISSUE THREAD

**Issue by JeeMo** [VML/Drupal-KIT-Docksal-Commands#3]
`fin run kit/phpcbf` fails with 'file not found' in the 8.0.x versions.  It is repaired in 8.1.x versions but they have a bug with vmlyr-drupal/kit and the pre-commit hook.

**Comment by JeeMo** [comment]
This patch replaces the phpcbf call to match 8.1.x.
Unfortunately, github won't allow a .patch file.

[phpcbf_fail.patch.txt](https://github.com/VML/Drupal-KIT-Docksal-Commands/files/3135265/phpcbf_fail.patch.txt)

**Comment by spfaffly** [comment]
Looks like this was updated in this commit by @garrettrathbone :
https://github.com/VML/Drupal-KIT-Docksal-Commands/commit/b9a4ba2fc695f871c4d468f6adf619effaa5168c#diff-8b28fe52c3cfbc62fea44431050da520
